from isaaclab.envs.mdp import *

from .actions.action_cfg import ActionOverridenJointPositionActionCfg
from .commands.commands_cfg import (
    BaseHeightRefCommandCfg,
    BaseLinVelRefCommandCfg,
    HeadingErrorRefCommandCfg,
    HeadingRefCommandCfg,
    JointPosErrRefCommandCfg,
    JointPosRefCommandCfg,
    JointVelRefCommandCfg,
    LinkPosErrRefCommandCfg,
    LinkPosRefCommandCfg,
    LinkRefCommandCfg,
    LinkRotErrRefCommandCfg,
    LinkRotRefCommandCfg,
    PoseRefCommandCfg,
    PositionRefCommandCfg,
    ProjectedGravityRefCommandCfg,
    RotationRefCommandCfg,
    ShadowingCommandBaseCfg,
    TimeToTargetCommandCfg,
)
from .commands.shadowing_command import (
    BaseHeightRefCommand,
    BaseLinVelRefCommand,
    HeadingErrorRefCommand,
    HeadingRefCommand,
    JointPosErrRefCommand,
    JointPosRefCommand,
    JointVelRefCommand,
    LinkPosErrRefCommand,
    LinkPosRefCommand,
    LinkRefCommand,
    LinkRotErrRefCommand,
    LinkRotRefCommand,
    PoseRefCommand,
    PositionRefCommand,
    ProjectedGravityRefCommand,
    RotationRefCommand,
    ShadowingCommandBase,
    TimeToTargetCommand,
)
from .curriculums.motion_reference import (
    BeyondConcatMotionAdaptiveWeighting,
    BeyondMimicAdaptiveWeighting,
    compute_smoothed_probs,
    compute_sums,
    update_current_fail_counters,
)
from .events.motion_reference import (
    beyondmimic_bin_fail_counter_smoothing,
    match_motion_ref_with_scene,
    reset_rigid_objects_state_by_reference,
    reset_robot_state_by_reference,
    update_rigid_objects_state_by_reference,
)
from .events.randomization import (
    randomize_actuator_gains,
    randomize_camera_offsets,
    randomize_default_joint_pos,
    randomize_ray_offsets,
)
from .events.terrain import register_virtual_obstacle_to_sensor
from .observations.body import (
    base_heading_w,
    base_pos_offset_since_motion_refresh,
    link_pos_b,
    link_quat_b,
    link_tannorm_b,
    root_tannorm_w,
)
from .observations.command import command_mask
from .observations.expanded import (
    expanded_base_ang_vel,
    expanded_joint_pos_rel,
    expanded_joint_vel,
    expanded_last_action,
    expanded_projected_gravity,
)
from .observations.exteroception import delayed_visualizable_image, visualizable_image
from .observations.motion_reference import (
    motion_reference_mask,
    pose_ref_mask,
    pose_ref_mask_legacy,
    ref_frame_interval,
    reference_progress,
    time_from_reference_update,
)
from .observations.reference_as_state import (
    base_ang_vel_reference_as_state,
    base_lin_vel_reference_as_state,
    base_pos_offset_reference_as_state,
    base_pos_z_reference_as_state,
    heading_reference_as_state,
    joint_pos_err_reference_as_state,
    joint_pos_reference_as_state,
    joint_pos_rel_reference_as_state,
    joint_vel_reference_as_state,
    joint_vel_rel_reference_as_state,
    link_pos_err_reference_as_state,
    link_pos_reference_as_state,
    link_quat_reference_as_state,
    link_tannorm_err_reference_as_state,
    link_tannorm_reference_as_state,
    projected_gravity_reference_as_state,
    root_tannorm_reference_as_state,
)
from .observations.reference_masked_proprioception import (
    joint_pos_reference_masked,
    joint_pos_rel_reference_masked,
    link_pos_reference_masked,
)
from .rewards.motion_reference import (
    base_position_imitation_gauss,
    base_position_offset_imitation_gauss,
    base_position_offset_imitation_square,
    base_position_tracking_gauss,
    base_position_tracking_neg_log,
    base_projected_gravity_tracking_gauss,
    base_rot_imitation_gauss,
    base_rot_imitation_square,
    base_rot_tracking_cos,
    base_rot_tracking_gauss,
    base_velocity_imitation_gauss,
    base_velocity_imitation_square,
    joint_pos_imitation_gauss,
    joint_pos_imitation_square,
    joint_pos_tracking_gauss,
    joint_pos_tracking_gauss_normalized,
    joint_pos_tracking_square,
    joint_vel_imitation_gauss,
    joint_vel_imitation_square,
    link_ang_vel_imitation_gauss,
    link_lin_vel_imitation_gauss,
    link_pos_imitation_gauss,
    link_pos_imitation_neg_log,
    link_pos_imitation_square,
    link_pos_tracking_gauss,
    link_pos_tracking_square,
    link_rot_imitation_gauss,
    link_rot_tracking_gauss,
)
from .rewards.regularizations import (
    action_rate_direction_consistent,
    action_rate_direction_switch,
    action_rate_gauss,
    action_rate_order,
    applied_torque_limits_by_ratio,
    applied_torque_limits_gauss,
    applied_torque_limits_square,
    body_lin_acc_gauss,
    body_lin_acc_square,
    constant_reward,
    contact_air_time,
    contact_rotate,
    contact_slide,
    contact_stay_time,
    contact_switch,
    joint_acc_direction_switch,
    joint_acc_gauss,
    joint_acc_gauss_step,
    joint_acc_l2_step,
    joint_deviation_square,
    joint_err_gauss,
    joint_pos_limits_gauss,
    joint_torque_sign_switch,
    joint_torques_direction_switch,
    joint_torques_gauss,
    joint_torques_l2,
    joint_vel_direction_switch,
    joint_vel_gauss,
    motors_power_square,
)
from .rewards.shadowing_command import (
    track_joint_pos_shadowing_cmd_exp,
    track_joint_vel_shadowing_cmd_exp,
    track_link_pos_shadowing_cmd_exp,
    track_link_rot_shadowing_cmd_exp,
)
from .rewards.volume_points import step_safety, volume_points_penetration
from .terminations.general import (
    abnormal_ang_vel,
    abnormal_joint_acc,
    abnormal_joint_vel,
    abnormal_lin_vel,
    dataset_exhausted,
    illegal_reset_contact,
    terrain_out_of_bounds,
)
from .terminations.motion_reference import (
    joint_pos_far_from_ref,
    link_pos_far_from_ref,
    pos_far_from_ref,
    projected_gravity_far_from_ref,
    rot_far_from_ref,
)
